<?php

use App\Http\Controllers\Authorize;
use App\Http\Controllers\Blockchain;
use App\Http\Controllers\Cashmaal;
use App\Http\Controllers\CoinbaseCommerce;
use App\Http\Controllers\Coingate;
use App\Http\Controllers\Coinpayments;
use App\Http\Controllers\CoinpaymentsFiat;
use App\Http\Controllers\Flutterwave;
use App\Http\Controllers\Instamojo;
use App\Http\Controllers\MercadoPago;
use App\Http\Controllers\Mollie;
use App\Http\Controllers\NMI;
use App\Http\Controllers\Payeer;
use App\Http\Controllers\Paypal;
use App\Http\Controllers\PaypalSdk;
use App\Http\Controllers\Paystack;
use App\Http\Controllers\Paytm;
use App\Http\Controllers\PerfectMoney;
use App\Http\Controllers\Razorpay;
use App\Http\Controllers\Skrill;
use App\Http\Controllers\Stripe;
use App\Http\Controllers\StripeJs;
use App\Http\Controllers\StripeV3;
use App\Http\Controllers\TwoCheckout;
use App\Http\Controllers\Voguepay;
use Illuminate\Support\Facades\Route;

Route::post('paypal', [Paypal\ProcessController::class, 'ipn'])->name('Paypal');
Route::get('paypal-sdk', [PaypalSdk\ProcessController::class, 'ipn'])->name('PaypalSdk');
Route::post('perfect-money', [PerfectMoney\ProcessController::class, 'ipn'])->name('PerfectMoney');
Route::post('stripe', [Stripe\ProcessController::class, 'ipn'])->name('Stripe');
Route::post('stripe-js', [StripeJs\ProcessController::class, 'ipn'])->name('StripeJs');
Route::post('stripe-v3', [StripeV3\ProcessController::class, 'ipn'])->name('StripeV3');
Route::post('skrill', [Skrill\ProcessController::class, 'ipn'])->name('Skrill');
Route::post('paytm', [Paytm\ProcessController::class, 'ipn'])->name('Paytm');
Route::post('payeer', [Payeer\ProcessController::class, 'ipn'])->name('Payeer');
Route::post('paystack', [Paystack\ProcessController::class, 'ipn'])->name('Paystack');
Route::post('voguepay', [Voguepay\ProcessController::class, 'ipn'])->name('Voguepay');
Route::get('flutterwave/{trx}/{type}', [Flutterwave\ProcessController::class, 'ipn'])->name('Flutterwave');
Route::post('razorpay', [Razorpay\ProcessController::class, 'ipn'])->name('Razorpay');
Route::post('instamojo', [Instamojo\ProcessController::class, 'ipn'])->name('Instamojo');
Route::get('blockchain', [Blockchain\ProcessController::class, 'ipn'])->name('Blockchain');
Route::post('coinpayments', [Coinpayments\ProcessController::class, 'ipn'])->name('Coinpayments');
Route::post('coinpayments-fiat', [CoinpaymentsFiat\ProcessController::class, 'ipn'])->name('CoinpaymentsFiat');
Route::post('coingate', [Coingate\ProcessController::class, 'ipn'])->name('Coingate');
Route::post('coinbase-commerce', [CoinbaseCommerce\ProcessController::class, 'ipn'])->name('CoinbaseCommerce');
Route::get('mollie', [Mollie\ProcessController::class, 'ipn'])->name('Mollie');
Route::post('cashmaal', [Cashmaal\ProcessController::class, 'ipn'])->name('Cashmaal');
Route::post('mercado-pago', [MercadoPago\ProcessController::class, 'ipn'])->name('MercadoPago');
Route::post('authorize', [Authorize\ProcessController::class, 'ipn'])->name('Authorize');
Route::get('nmi', [NMI\ProcessController::class, 'ipn'])->name('NMI');
Route::any('two-checkout', [TwoCheckout\ProcessController::class, 'ipn'])->name('TwoCheckout');
